### ISSUE TITLE
example?

### ISSUE THREAD

**Issue by Chriscxa** [NerdmindDE/BigPipe#2]
Hey hi. 

I load for testing a external php with pageletData via Ajax.
All working fine and is loading. But the loaded html.content stay in `<code class="hidden" id="_2secondID"><!-- <section id="red" class="text">Im second</section> --></code>`
`<script></script>`

to load the pagelet via ajax i use:
`$(document).ready(function(){
      $("#click").click(function(){
           BigPipe.reset();
           $("#content").load('home.php');
  });
});`

can you tell whats wrong?
Thanx for help and script

**Comment by Nerdmind** [comment]
Hi, nice to hear you again. :-)

I am trying to understand your problem. Is it correct that the problem is the following: The HTML content from the pagelet within the ajax response get not injected into the page? Is there any javascript error message or something which can help?

Can you show me an example of the FULL ajax response and how you handle this, so that I can figure out how you doing this?

**Comment by Chriscxa** [comment]
hey hi. thanx for help.
Is only a testSample to load second pagelet via ajax.
Now got it, but got js.error. Not all phases done. Got only two.
Js not executed... remove child etc
Upload it here: https://github.com/Chriscxa/test

**Comment by Chriscxa** [comment]
![erlog](https://cloud.githubusercontent.com/assets/10387769/14737588/15a5cbc0-087d-11e6-9bb5-1c436c8f0e2b.JPG)

**Comment by Nerdmind** [comment]
Hi, I've write a example with loading over an transport frame: **LINK DELETED; SEE UPDATE** This made some adjustments necessary to the PHP and JS files but it works fine (only tested on Firefox / Linux). The transport frame is also the method how Facebook loads his Bootloader content asynchronously – and I think it is the best. Previously I've had also the AJAX solution but it wasn't good enough.

This solution is not perfect but especially for you as an example. In a perfect solution you would have a history manager which change the URL on the address bar and also replace the window title with the title from the new page.

I would long ago have a better solution if I've an idea how I can do this so that it works **easy** for everyone. The problem is, that it is complex and depends on project in which BigPipe is used.

I hope that the example help you to understand how I load the content via transport frame and that you find a good solution to include it into your project. :-)

**UPDATE:**
Okay, I've update the repository with new code and a `async.php` which contains all additional code to handle the async request. No more changes on the BigPipe core and the PHP classes are required. The only difference from the "normal version" is in the `async.php` whichs load the page on link click over a transport frame.

What you have to do:
1.) Download the current version of BigPipe from the repository which contains multiple code changes on the JS and PHP classes.
2.) Open the `async.php` in your browser and see how it works.

:-)

**Comment by Chriscxa** [comment]
Woha, thanx thanx thanx. 
No problem for title & link. We extend your script. Checking ajax: `function is_ajax() {
    if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == "xmlhttprequest") {
        return true;
    }
    return false;
}` 
if the request is from ajax for routing. 
After that we can use a render() for complete site or transportframe.
For the url we extend with someting like this (clientside): 
function loadPage(url, f){
    window.onpopstate = function(e) {
        loadPage(window.location, true);
    }
    initLoading();
    $.ajax({
        url : url,
        cache : false,
        dataType : 'json',
        type : 'GET',
        success : function(data) {
            var content = data.content;
            var container = data.container;
            var title = data.title;
            $(container).html(content);
            document.title = title;
            Pusher.setPageTitle(document.title);
            window.history.pushState({},'New URL:' + url, url);
            $('body').click().animate({scrollTop : 0}, 200);
            reloadInits();
            stopLoading();
        },
        error : function() {
            stopLoading();
            login_required();
        }
    });
    return false;
}
**many thanx for help**
