### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Chriscxa** [NerdmindDE/BigPipe#3]
Parse error: syntax error, unexpected ':', expecting ';' or '{' in F:\xampp\htdocs\BigPipe-master\include\classes\BigPipe\BigPipe.php on line 33
hmm... only php7 code.

**Comment by Nerdmind** [comment]
Hi. I don't want to support older versions of PHP7 because PHP7 is available since more than 8 months and brings an enormous performance boost (ideal for high-performance websites which uses BigPipe). In addition, any reasonable PHP5.4 project should run under PHP7. So nothing speaks against PHP7 to install (of course, if someone still use such crap functions like `mysql_*` or something similar which has been declared as deprecated since a couple of versions in it's project, it will not run under PHP7).

If you want to continue to use BigPipe under < PHP7, then you need to remove the return type declarations like `: bool`, `: int` or `: Resource` and convert null coalescing operators (`??`) to the old version. That should not be so much work. Is this okay?

**Comment by Nerdmind** [comment]
> If you want to continue to use BigPipe under < PHP7, then you need to remove the return type declarations like `: bool`, `: int` or `: Resource` and convert null coalescing operators (`??`) to the old version. That should not be so much work. Is this okay?

Hi again. No response from you, but [I just have done this work for you](https://nmnd.de/temp/bigpipe-php5-842379e0ca399bdb5f8b85c455d1136b519d1816.tar.gz) and tested it with PHP 5.6.
